FROM node:10 as builder

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm i -g serve
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

RUN npm run build

FROM node:10 as final

WORKDIR /usr/share/app

COPY --from=builder usr/src/app/build /usr/share/app

RUN serve -l $PORT